### ISSUE TITLE
`[TCPSOCKET] closed by remote host` after BNLS connect when running more than two bots from the same ip

### ISSUE THREAD

**Issue by PhilippHeuer** [uakfdotb/ghostpp#15]
When more than 2 bots get scheduled on the same host within my kubernetes cluster (same public ip)  the bot can't connect to battle.net anymore.
When the 3rd one starts - sharing the same public ip - it just waits 90 seconds after the BNLS connect and then gets the disconnected after a short while without any errors.
The first 2 started bots always work, regardless of which one it is. All bots are identical except for acc/cdkeys/command trigger/bnls warden cookie/mysql bot id (docker container, configured using environment variables).

Does someone have a idea what could cause this?

Log
```
[BNET: USEast] connected
[BNET: USWest] connected
[BNET: Europe] connected
[BNET: Asia] connected
[BNET: USEast] attempting to auth as Warcraft III: The Frozen Throne
[BNET: USEast] creating BNLS client
[BNLSC: pyro.no-ip.biz:9367:C22] connecting to server [pyro.no-ip.biz] on port 9367
[BNET: Europe] attempting to auth as Warcraft III: The Frozen Throne
[BNET: Europe] creating BNLS client
[BNLSC: pyro.no-ip.biz:9367:C20] connecting to server [pyro.no-ip.biz] on port 9367
[BNET: Asia] attempting to auth as Warcraft III: The Frozen Throne
[BNET: Asia] creating BNLS client
[BNLSC: pyro.no-ip.biz:9367:C21] connecting to server [pyro.no-ip.biz] on port 9367
[BNLSC: pyro.no-ip.biz:9367:C22] connected
[BNET: USWest] attempting to auth as Warcraft III: The Frozen Throne
[BNET: USWest] creating BNLS client
[BNLSC: pyro.no-ip.biz:9367:C23] connecting to server [pyro.no-ip.biz] on port 9367
[BNLSC: pyro.no-ip.biz:9367:C20] connected
[BNLSC: pyro.no-ip.biz:9367:C21] connected
[BNLSC: pyro.no-ip.biz:9367:C23] connected
[TCPSOCKET] closed by remote host
[BNET: USEast] disconnected from battle.net
[BNET: USEast] waiting 90 seconds to reconnect
[TCPSOCKET] closed by remote host
[BNET: USWest] disconnected from battle.net
[BNET: USWest] waiting 90 seconds to reconnect
[TCPSOCKET] closed by remote host
[BNET: Europe] disconnected from battle.net
[BNET: Europe] waiting 90 seconds to reconnect
[TCPSOCKET] closed by remote host
[BNET: Asia] disconnected from battle.net
[BNET: Asia] waiting 90 seconds to reconnect
```

**Comment by uakfdotb** [comment]
Did you update bncsutil? #12

**Comment by PhilippHeuer** [comment]
Yes, i upgraded to bncsutil v1.4.1. I also don't think there is a relation since two of my bots are running fine since i started them, the issue only occurs when the 3rd one starts with the same public ip.

**Comment by uakfdotb** [comment]
It could be related since this issue is entirely on Battle.net side (Battle.net accepts your first two connections but decided not to accept the third one). I had strange problem where CD keys purchased several years ago work fine with old bncsutil (meaning invalid SID_AUTH_CHECK packet), but newly purchased keys hang in the same way. Upgrading bncsutil fixed that.

Are you sure that the bncsutil is upgraded correctly? A simple way to make sure the new version is being used is to go to the source code of new version, add a debug line like this in getExeInfo function in checkrevision.cpp:

```
printf("yup this is the new version\n");
```

And then recompile and make sure you see that print line.

Otherwise probably Battle.net just decided to limit the number of connections from your IP to 2 instead of the 8 connections it used to accept. Maybe for some non-residential IP ranges they are having stricter limits.

**Comment by PhilippHeuer** [comment]
Im sure, i removed stormlib/bncsutil from the repo in my fork to build from source, i'm not really a fan of copying source files from another repo and since im building a container i can do it just fine in my case.

--> https://github.com/docker-gameserver/ghostpp/blob/master/.gitlab-ci.yml

Section:
```
  - git clone https://github.com/BNETDocs/bncsutil.git
  - cd bncsutil
  - git checkout v1.4.1
  - cmake -G "Unix Makefiles" -B./build -H./
  - cd build && make && make install
```

Would be pretty sad if the set it down to 2 from 8 :( I will try to run 3 containers locally and check if it works with my residential ip.

**Comment by PhilippHeuer** [comment]
Works from my local ip ... great. Guess they set the limit to 2 for known datacenters or sth. Also tried it on DigitalOcean/Amazon real quick for refence and i can't start more than 2 bots either :(

**Comment by PhilippHeuer** [comment]
Another note for other ppl. finding this, do not let your 3+th bot runnning if it keeps reconnecting - you'r gonna get ip banned.
