### ISSUE TITLE
Kick Slot

### ISSUE THREAD

**Issue by ziadoma** [uakfdotb/ghostpp#19]
Could it be possible to to make the commands work on slots? P.e. !kick slot1. 
I think that would be a good feature with all the spoofs and colored names happening on battle.net.

**Comment by truedesire** [comment]
> Could it be possible to to make the commands work on slots? P.e. !kick slot1.
> I think that would be a good feature with all the spoofs and colored names happening on battle.net.

Try !open slot№

**Comment by ziadoma** [comment]
Was talking about ingame

**Comment by kirill-782** [comment]
You can get payload size. IF > 2 - kick by name else - kick by SID + 1 (like open command whout change slot)

**Comment by uakfdotb** [comment]
I don't want to implement it in this version, but you can patch it yourself with @kirill-782's suggestion. See the code for !kick and !open in game.cpp, you'll need to make modifications to !kick to be similar to !open (use GetPlayerFromSID to get CGamePlayer* object from the slot ID).
