### ISSUE TITLE
Lock

### ISSUE THREAD

**Issue by kirill-782** [uakfdotb/ghostpp#2]
```
	boost::mutex::scoped_lock lock( m_GamesMutex );

	if( m_CurrentGame )
	{
		for( vector<CBNET *> :: iterator i = m_BNETs.begin( ); i != m_BNETs.end( ); ++i )
		{
			if( (*i)->GetServer( ) == creatorServer )
				(*i)->QueueChatCommand( m_Language->UnableToCreateGameAnotherGameInLobby( gameName, m_CurrentGame->GetDescription( ) ), creatorName, whisper );
		}

		if( m_AdminGame )
			m_AdminGame->SendAllChat( m_Language->UnableToCreateGameAnotherGameInLobby( gameName, m_CurrentGame->GetDescription( ) ) );

		**return;**
	}

	if( m_Games.size( ) >= m_MaxGames )
	{
		for( vector<CBNET *> :: iterator i = m_BNETs.begin( ); i != m_BNETs.end( ); ++i )
		{
			if( (*i)->GetServer( ) == creatorServer )
				(*i)->QueueChatCommand( m_Language->UnableToCreateGameMaxGamesReached( gameName, UTIL_ToString( m_MaxGames ) ), creatorName, whisper );
		}

		if( m_AdminGame )
			m_AdminGame->SendAllChat( m_Language->UnableToCreateGameMaxGamesReached( gameName, UTIL_ToString( m_MaxGames ) ) );

		**return;**
	}

	**lock.unlock( );**
```
Is there not to be an unlock before the return?

**Comment by uakfdotb** [comment]
The scoped_lock should automatically unlock when the program exits the scope in which it is defined.

**Comment by kirill-782** [comment]
And are they used to ensure that other threads can not access simultaneously to the same objects?

**Comment by uakfdotb** [comment]
Yes.

**Comment by kirill-782** [comment]
If Mutex is blocked, then blocking the same Mutex will lead to waiting until the first one unlocks it?

**Comment by uakfdotb** [comment]
Yes. The scoped_lock automatically unlocks when the program exits the scope in which it is defined. (e.g., when we return from the function)

**Comment by uakfdotb** [comment]
You can read more at http://www.boost.org/doc/libs/1_60_0/doc/html/boost/interprocess/scoped_lock.html

**Comment by Karaulov** [comment]
Possible just remove boost from ghost ?

Now filesystem, mutex, thread can be found in std

**Comment by uakfdotb** [comment]
Should be possible. But I'm not planning on working on this anymore other than fixing bugs. Feel free to fork and/or send a pull request!
