### ISSUE TITLE
Game version too old error - Patch 1.29

### ISSUE THREAD

**Issue by eap53** [uakfdotb/ghostpp#3]
Still getting this error after making changes on windows:

[BNET: USWest] attempting to auth as Warcraft III: The Frozen Throne
[BNET: USWest] creating BNLS client
[BNLSC: localhost:9367:C1] connecting to server [localhost] on port 9367
[BNET: USWest] logon failed - game version is too old, disconnecting
[BNET: USWest] disconnected from battle.net
[BNET: USWest] waiting 90 seconds to reconnect

I've tried renaming my Warcraft III.exe inside my Warcraft III folder and also redirecting the bot_war3path inside the default.cfg. I have also extracted common.j and blizzard.j from my War3x.mpq and put them in the bots mapcfgs folder. I saw on another thread that replacing storm.dll and game.dll with empty files fixes the issue, however when I tried that I get this error: 

[BNCSUI] unable to open [C:\Program Files (x86)\Warcraft III\storm.dll]
[BNCSUI] unable to open [C:\Program Files (x86)\Warcraft III\game.dll]
[BNET: USWest] logon failed - bncsutil key hash failed (check your Warcraft 3 path and cd keys), disconnecting
[BNET: USWest] disconnected from battle.net
[BNET: USWest] waiting 90 seconds to reconnect

I've also had similar issues with aurabot and the older version of GHost++ since the 1.29 patch.

Here's my default.cfg with stuff taken out:
[default cfg copy.txt](https://github.com/uakfdotb/ghostpp/files/1922745/default.cfg.copy.txt)

**Comment by uakfdotb** [comment]
Did you recompile from source? The ghost.exe is outdated. I do not have the software to recompile from source on Windows at the moment, I will look into it.

**Comment by dkglund** [comment]
I got same error. We hope you get the software to recompile from source on Windows ! :D

**Comment by Stannnnn** [comment]
![image](https://user-images.githubusercontent.com/11667076/39440160-569afa1a-4caa-11e8-9349-47da07a3c364.png)

Tried to recompile it for windows however getting this error when a game ends. Any idea? @uakfdotb

**Comment by uakfdotb** [comment]
I was not able to figure out how to get libgmp working in Visual Studio 2017.

@Stannnnn do you have a debug trace for that error? Otherwise it is hard to debug.

**Comment by Stannnnn** [comment]
I'm using visual c++ 2008 express edition.
Just realised that I was using the Debug MySQL instead of Release MySQL config.
Seems to work now without crash.

**Comment by uakfdotb** [comment]
OK awesome thanks!

@eap53 @dkglund you can try the binary from Stannnn https://github.com/uakfdotb/ghostpp/raw/master/ghost.exe
